export const feedingFrequencyOptions = [
  { label: "Kilka razy w tygodniu", value: "few_times_week" },
  { label: "Raz w tygodniu", value: "once_week" },
  { label: "Raz na dwa tygodnie", value: "once_two_weeks" },
  { label: "Raz w miesiącu", value: "once_month" },
  { label: "Rzadziej", value: "rarely" },
];

export const spiderSpeciesList = [
  { label: "Brachypelma hamorii", value: "Brachypelma hamorii" },
  { label: "Brachypelma albopilosum", value: "Brachypelma albopilosum" },
  {
    label: "Chromatopelma cyaneopubescens",
    value: "Chromatopelma cyaneopubescens",
  },
  { label: "Aphonopelma chalcodes", value: "Aphonopelma chalcodes" },
  { label: "Grammostola rosea", value: "Grammostola rosea" },
  { label: "Grammostola cala", value: "Grammostola cala" },
  { label: "Lasiodora parahybana", value: "Lasiodora parahybana" },
  { label: "Phidippus regius", value: "Phidippus regius" },
  { label: "Phidippus audax", value: "Phidippus audax" },
  { label: "Salticus scenicus", value: "Salticus scenicus" },
  { label: "Salticus cingulatus", value: "Salticus cingulatus" },
  { label: "Marpissa muscosa", value: "Marpissa muscosa" },
  { label: "Menemerus semilimbatus", value: "Menemerus semilimbatus" },
  { label: "Araneus diadematus", value: "Araneus diadematus" },
  { label: "Araneus quadratus", value: "Araneus quadratus" },
  { label: "Neoscona crucifera", value: "Neoscona crucifera" },
  { label: "Cyclosa conica", value: "Cyclosa conica" },
  { label: "Zygiella x-notata", value: "Zygiella x-notata" },
  { label: "Lycosa tarantula", value: "Lycosa tarantula" },
  { label: "Lycosa tarentula", value: "Lycosa tarentula" },
  { label: "Hogna radiata", value: "Hogna radiata" },
  { label: "Pardosa amentata", value: "Pardosa amentata" },
  { label: "Pardosa palustris", value: "Pardosa palustris" },
  { label: "Agelena labyrinthica", value: "Agelena labyrinthica" },
  { label: "Tegenaria domestica", value: "Tegenaria domestica" },
  { label: "Tegenaria atrica", value: "Tegenaria atrica" },
  { label: "Coelotes terrestris", value: "Coelotes terrestris" },
  { label: "Araneus marmoreus", value: "Araneus marmoreus" },
  { label: "Loxosceles reclusa", value: "Loxosceles reclusa" },
  { label: "Loxosceles deserta", value: "Loxosceles deserta" },
  { label: "Loxosceles laeta", value: "Loxosceles laeta" },
  { label: "Latrodectus mactans", value: "Latrodectus mactans" },
  { label: "Latrodectus hesperus", value: "Latrodectus hesperus" },
  { label: "Latrodectus geometricus", value: "Latrodectus geometricus" },
  { label: "Argyroneta aquatica", value: "Argyroneta aquatica" },
];

export const individualTypeOptions = [
  { label: "Samiec", value: "Samiec" },
  { label: "Samica", value: "Samica" },
  { label: "Niezidentyfikowany", value: "Niezidentyfikowany" },
];
