export const feedingFrequencyOptions = [
  { label: "Kilka razy w tygodniu", value: "few_times_week" },
  { label: "Raz w tygodniu", value: "once_week" },
  { label: "Raz na dwa tygodnie", value: "once_two_weeks" },
  { label: "Raz w miesiącu", value: "once_month" },
  { label: "Rzadziej", value: "rarely" },
];

export const spiderSpeciesList = [
  { label: "Brachypelma hamorii", value: "brachypelma_hamorii" },
  { label: "Brachypelma albopilosum", value: "brachypelma_albopilosum" },
  {
    label: "Chromatopelma cyaneopubescens",
    value: "chromatopelma_cyaneopubescens",
  },
  { label: "Aphonopelma chalcodes", value: "aphonopelma_chalcodes" },
  { label: "Grammostola rosea", value: "grammostola_rosea" },
  { label: "Grammostola cala", value: "grammostola_cala" },
  { label: "Lasiodora parahybana", value: "lasiodora_parahybana" },
  { label: "Phidippus regius", value: "phidippus_regius" },
  { label: "Phidippus audax", value: "phidippus_audax" },
  { label: "Salticus scenicus", value: "salticus_scenicus" },
  { label: "Salticus cingulatus", value: "salticus_cingulatus" },
  { label: "Marpissa muscosa", value: "marpissa_muscosa" },
  { label: "Menemerus semilimbatus", value: "menemerus_semilimbatus" },
  { label: "Araneus diadematus", value: "araneus_diadematus" },
  { label: "Araneus quadratus", value: "araneus_quadratus" },
  { label: "Neoscona crucifera", value: "neoscona_crucifera" },
  { label: "Cyclosa conica", value: "cyclosa_conica" },
  { label: "Zygiella x-notata", value: "zygiella_x_notata" },
  { label: "Lycosa tarantula", value: "lycosa_tarantula" },
  { label: "Lycosa tarentula", value: "lycosa_tarentula" },
  { label: "Hogna radiata", value: "hogna_radiata" },
  { label: "Pardosa amentata", value: "pardosa_amentata" },
  { label: "Pardosa palustris", value: "pardosa_palustris" },
  { label: "Agelena labyrinthica", value: "agelena_labyrinthica" },
  { label: "Tegenaria domestica", value: "tegenaria_domestica" },
  { label: "Tegenaria atrica", value: "tegenaria_atrica" },
  { label: "Coelotes terrestris", value: "coelotes_terrestris" },
  { label: "Araneus marmoreus", value: "araneus_marmoreus" },
  { label: "Loxosceles reclusa", value: "loxosceles_reclusa" },
  { label: "Loxosceles deserta", value: "loxosceles_deserta" },
  { label: "Loxosceles laeta", value: "loxosceles_laeta" },
  { label: "Latrodectus mactans", value: "latrodectus_mactans" },
  { label: "Latrodectus hesperus", value: "latrodectus_hesperus" },
  { label: "Latrodectus geometricus", value: "latrodectus_geometricus" },
  { label: "Argyroneta aquatica", value: "argyroneta_aquatica" },
];
